// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_3PlTpC6bQo_h1OUUbyIUPj8xYqbZ5jM',
    appId: '1:270697614748:web:11eaea51e5b7ee21e0cc59',
    messagingSenderId: '270697614748',
    projectId: 'my-task-manager-8aebc',
    authDomain: 'my-task-manager-8aebc.firebaseapp.com',
    storageBucket: 'my-task-manager-8aebc.firebasestorage.app',
    measurementId: 'G-W1PXG15QRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC78A1YAMQBsign6lMu4LG88vzNJXz-2xU',
    appId: '1:270697614748:android:4e0bf65ab64370bae0cc59',
    messagingSenderId: '270697614748',
    projectId: 'my-task-manager-8aebc',
    storageBucket: 'my-task-manager-8aebc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPEJef_NuAYTpHh86tbpVV7un33sw7aq0',
    appId: '1:270697614748:ios:8e721e3dfd29810de0cc59',
    messagingSenderId: '270697614748',
    projectId: 'my-task-manager-8aebc',
    storageBucket: 'my-task-manager-8aebc.firebasestorage.app',
    iosBundleId: 'com.example.mytaskmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPEJef_NuAYTpHh86tbpVV7un33sw7aq0',
    appId: '1:270697614748:ios:8e721e3dfd29810de0cc59',
    messagingSenderId: '270697614748',
    projectId: 'my-task-manager-8aebc',
    storageBucket: 'my-task-manager-8aebc.firebasestorage.app',
    iosBundleId: 'com.example.mytaskmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_3PlTpC6bQo_h1OUUbyIUPj8xYqbZ5jM',
    appId: '1:270697614748:web:2f8468b935560c7be0cc59',
    messagingSenderId: '270697614748',
    projectId: 'my-task-manager-8aebc',
    authDomain: 'my-task-manager-8aebc.firebaseapp.com',
    storageBucket: 'my-task-manager-8aebc.firebasestorage.app',
    measurementId: 'G-CLZ1PR7XGL',
  );
}
